#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dlnaspect01")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDim_Out(Dim_Out instance);
    partial void UpdateDim_Out(Dim_Out instance);
    partial void DeleteDim_Out(Dim_Out instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WpfApplication3.Properties.Settings.Default.dlnaspect01ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dim_Over> Dim_Overs
		{
			get
			{
				return this.GetTable<Dim_Over>();
			}
		}
		
		public System.Data.Linq.Table<Dim_Out> Dim_Outs
		{
			get
			{
				return this.GetTable<Dim_Out>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="[CSFB\\agurha1].Dim_Over")]
	public partial class Dim_Over
	{
		
		private string _id;
		
		private System.Nullable<bool> _displayed;
		
		public Dim_Over()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayed", DbType="Bit")]
		public System.Nullable<bool> displayed
		{
			get
			{
				return this._displayed;
			}
			set
			{
				if ((this._displayed != value))
				{
					this._displayed = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="[CSFB\\agurha1].Dim_Out")]
	public partial class Dim_Out : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _comb;
		
		private string _wd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncombChanging(string value);
    partial void OncombChanged();
    partial void OnwdChanging(string value);
    partial void OnwdChanged();
    #endregion
		
		public Dim_Out()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comb", DbType="NVarChar(50)")]
		public string comb
		{
			get
			{
				return this._comb;
			}
			set
			{
				if ((this._comb != value))
				{
					this.OncombChanging(value);
					this.SendPropertyChanging();
					this._comb = value;
					this.SendPropertyChanged("comb");
					this.OncombChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wd", DbType="NVarChar(50)")]
		public string wd
		{
			get
			{
				return this._wd;
			}
			set
			{
				if ((this._wd != value))
				{
					this.OnwdChanging(value);
					this.SendPropertyChanging();
					this._wd = value;
					this.SendPropertyChanged("wd");
					this.OnwdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
